# Generated by Django 4.1.5 on 2023-02-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
